
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 

# Docker Compose Version
version: '3.1'

# Services
Services:

  # nginx service
  nginx_service:
    container_name: nginx_container
    image_name: nginx_image
    restart: on-failure
    #build: .
    build:
      context: .
      dockerfile: Nginx-Dockerfile
    ports: 
      - "1111:80"
    networks:
      - nginx_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html

# Networks
networks:
  nginx_network:
    name: nginx_network
    driver: bridge


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
