# docker-compose --version
# docker-compose up
# docker-compose up -d
# docker-compose down
# docker-compose restart
# docker-compose ps
#
# docker-compose -f SonarQube-Docker-Compose.yml up
# docker-compose -f SonarQube-Docker-Compose.yml up -d

# command: sleep infinity => Docker konteynerların sürekli çalışmasını sağlamak için kullanılan linux komutudur.
# Bu komut konteynarların arka planda sürekli çalışmasını sağlar ve belirli bir görev veya işlem yapılmadığı durumlarda kapanmasını engeller


# restart: on-failure => Docker Container çökmesi halinde otomatik başlat
# restart: no=> Default Yani docker container otomatik olarak restart yapsın
# restart: unless-stopped: Container durduğında otomatik başlasın
# restart: always: Docker Container  her zaman otomatik başlasın


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 

# Docker Compose Version
version: '3.1'

# Services
services:

  # nginx service
  nginx_service:
    container_name: nginx_container
    image: nginx_image
    restart: on-failure
    #build: .
    build:
      context: .
      dockerfile: Nginx-Dockerfile
    ports: 
      - "1111:80"
    networks:
      - nginx_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html

# Networks
networks:
  nginx_network:
    name: nginx_network
    driver: bridge


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 

#  docker images
#  docker ps
#  docker ps -a
#  docker container exec -it <CONTAINER_ID> bash
#  winpty docker container exec -it <CONTAINER_ID> bash

#  winpty docker container exec -it sonarqube_postgres bash
#  \q => Çıkış
#  \l => Veritabanı Listelesin
#  \c sonarqube => Veritabana bağlan
#  \dt: Tabloları Listele
#  \d tabloAdi => Tablo özelliklerini göster

# docker volume ls
# docker volume inspect volumeID
# docker volume rm  volumeID
